name: securiport-proj1

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pip
  - pytest
  - pandas
  - pip:
    # Data Collection & Scraping
    - requests
    - beautifulsoup4
    - trafilatura

    # NLP & Hugging Face
    - transformers
    - sentencepiece
    - accelerate

    # Text preprocessing
    - nltk

    # API
    - fastapi
    - uvicorn

    # Utilities & Configuration
    - python-dotenv
    - pydantic